### PR TITLE
Replaced append with concat

### PR DESCRIPTION
**Pull request by berkott**
Didn't test changes but think they should work. Replacing the append with concat will get rid of the pandas FutureWarning.

### CODE REVIEW

**Comment by bes-dev** [comment]
:+1:

**Comment by MichaelMonashev** [comment]
@berkott , did you benchmark your solution?

**Comment by berkott** [comment]
As I said in the comment, I did not test the changes at all but I believe they should work.

**Comment by MichaelMonashev** [comment]
Затестил сейчас. Всё работает нормально. @berkott , спасибо!

**Pull request merged**
